# infra/menifests/server/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: grpc-chat
  labels:
    app: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/golang-grpc-chat:latest
          ports:
            - containerPort: 50051
