# infra/manifests/server/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: grpc-chat
spec:
  selector:
    app: grpc-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer
