apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: grpc-chat-cluster-v1-0
  region: ap-northeast-2

nodeGroups:
  - name: system-nodes
    instanceType: t3.small
    desiredCapacity: 1

fargateProfiles:
  - name: app-fargate
    selectors:
      - namespace: grpc-chat
      - namespace: argocd
