# infra/jenkins/jenkins-deployment.yaml

apiVersion: apps/v1
kind: Deployment   # 또는 StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        volumeMounts:
          - name: jenkins-workspace
            mountPath: /workspace      # Jenkins 워크스페이스로 쓸 경로
      volumes:
        - name: jenkins-workspace
          persistentVolumeClaim:
            claimName: jenkins        # PVC 이름