controller:
  admin:
    existingSecret: jenkins
  persistence:
    enabled: true
    size: 20Gi
    storageClass: gp2
  serviceType: LoadBalancer
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  serviceAccount:
    create: true
    name: jenkins
  ingress:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  nodeSelector:
    role: jenkins
  agent:
    customJenkinsLabels: jenkins-agent
    image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-agent-with-kubectl
    tag: latest
    alwaysPullImage: true

persistence:
  enabled: true
  storageClass: gp2
  size: 20Gi
