# infra/jenkins/values.yaml

controller:
  nodeSelector:
    role: jenkins
  tolerations:
    - key: "jenkins"
      operator: "Exists"
      effect: "NoSchedule"

  persistence:
    enabled: true
    existingClaim: ""
    storageClass: "gp2"
    size: 20Gi
    mountPath: /var/jenkins_home

  serviceType: LoadBalancer
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external

  resources:
    requests:
      cpu: "500m"
      memory: "1.5Gi"  
    limits:
      cpu: "2"
      memory: "2Gi"   

  ingress:
    enabled: false
    
  installPlugins: []          # 플러그인 자동 설치 비활성화
  initContainers: []          # init 컨테이너 없애기
  sidecars:
    configReload:
      enabled: false          # config reload 사이드카 비활성화