# infra/jenkins/values.yaml

controller:
  nodeSelector:
    role: jenkins
  tolerations:
    - key: "jenkins"
      operator: "Exists"
      effect: "NoSchedule"

  persistence:
    enabled: true
    existingClaim: jenkins
    storageClass: "gp2"
    size: 20Gi
    mountPath: /bitnami/jenkins

  serviceType: LoadBalancer
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external

  resources:
    requests:
      cpu: "500m"
      memory: "1.5Gi"  
    limits:
      cpu: "2"
      memory: "2Gi"   

  ingress:
    enabled: false
    
  installPlugins: []          # 플러그인 자동 설치 비활성화
  initContainers: []          # init 컨테이너 없애기
  sidecars:
    configReload:
      enabled: false          # config reload 사이드카 비활성화
  
  JCasC:
    enabled: true
    configScripts:
      agent-config: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                namespace: "jenkins"
                containerTemplates:
                  - name: jenkins-agent-kubectl
                    image: 935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-agent-kubectl
                    command: ["cat"]
                    ttyEnabled: true
                    resourceRequestCpu: "200m"
                    resourceRequestMemory: "512Mi"
                    resourceLimitCpu: "1"
                    resourceLimitMemory: "1Gi"
