apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job-ws
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: ecr-push-sa
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --dockerfile=ws-proxy/Dockerfile
            - --context=git://github.com/xxoznge/golang-grpc-chat.git#main
            - --destination=935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/ws-proxy:latest
            - --destination=935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/ws-proxy:${BUILD_NUMBER}
            - --skip-tls-verify
            - --snapshotMode=redo
            - --cache=true
          volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
      volumes:
        - name: kaniko-secret
          secret:
            secretName: ecr-docker-config
