# infra/kaniko/kaniko-job-web.yaml
 
apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-job-web
  namespace: jenkins
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      initContainers:
        - name: git-clone
          image: alpine/git
          command: ["sh", "-c"]
          args:
            - git clone --depth=1 https://github.com/xxoznge/golang-grpc-chat.git /workspace
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --context=dir:///workspace/web-chat
            - --dockerfile=Dockerfile
            - --destination=935875533840.dkr.ecr.ap-northeast-2.amazonaws.com/web-chat:latest
            - --cache=true
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
            - name: docker-config
              mountPath: /kaniko/.docker
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_session_token
      restartPolicy: Never
      volumes:
        - name: workspace-volume
          emptyDir: {}
        - name: docker-config
          secret:
            secretName: kaniko-docker-config
